### ISSUE TITLE
Compatible phone list

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/nokia-phone-arduino-shield#3]
The target phone is the Nokia 3100. Here is the full list of compatible phones that use commands from nk6510.c.: 6510, 6310, 8310, 6310i, 6360, 6610, 6100, 5100, 3510, 3510i, 3595, 6800, 6810, 6820, 6820b, 6610i, 6230, 6650, 7210, 7250, 7250i, 7600, 6170, 6020, 6230i, 5140, 5140i, 6021, 6500, 6220, 3120b, 3100, 3120, 6015i, 6101, 6680, 6280, 3220, 6136, 6233, 6822, 6300, 6030, 3110c, series60, series40

We can have a function that checks if the board is connected to one of these boards. If not, throw an error. This would probably be a waste of memeory.

**Comment by charlespax** [comment]
That list was given on some site. We have an issue to determine which gnokii protocol to use. See https://github.com/PaxInstruments/nokia-phone-arduino-shield/issues/8.

Closing issue.

**Comment by protological** [comment]
I don't think the 3100 was developed from the 6510, the Wikipedia page says it is from the 6100.  The 3110,3210 and 3310 are from the 6510.
