### ISSUE TITLE
Shield connector mismatch

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/nokia-phone-arduino-shield#5]
"It appears that the Nokia shield needs to be modified to match the connector. I was looking at the phone schematic and the connector pins don't match up with the TX and RX lines on the board. It looks like you have RX connected to the forth pin (p5) rather than the sixth pin (p7)." -Drew
![connector](https://cloud.githubusercontent.com/assets/281642/8330469/de2ecc9e-1a81-11e5-9fb9-581785961896.png)

"I think I was off by 1, it might be ok, confirming now" -Drew

**Comment by charlespax** [comment]
"I got confused with the RX/TX and the connector, I thought it was off by one. Good news, success getting a response from the phone!! I should be able to send a text to you and chris, send me your phone number" -Drew

**Comment by charlespax** [comment]
Okay, it there an actual problem here or was is just a counting issue? Are you talking about the connector mounted on the PCB or the cable?

Here is the schematic.

![screen shot 2015-06-24 at 15 12 42](https://cloud.githubusercontent.com/assets/281642/8330762/104330d8-1a84-11e5-9b4a-9916c91557a4.png)
![screen shot 2015-06-24 at 15 12 51](https://cloud.githubusercontent.com/assets/281642/8330765/16ed1db8-1a84-11e5-88d7-a1b3cf686d52.png)
![screen shot 2015-06-24 at 15 13 14](https://cloud.githubusercontent.com/assets/281642/8330774/21222d5a-1a84-11e5-89b7-091c762372cd.png)
![screen shot 2015-06-24 at 15 13 23](https://cloud.githubusercontent.com/assets/281642/8330775/2240528e-1a84-11e5-9b24-2359111eccd3.png)
![screen shot 2015-06-24 at 15 13 30](https://cloud.githubusercontent.com/assets/281642/8330776/233a6a1c-1a84-11e5-9b95-cf50207acce0.png)

**Comment by protological** [comment]
I looked at the schematic and traced out the connections and everything is good.  I was thinking from the processor side of things and not from the phone side, so I was trying to send to the phone's RX port.  Everything matches up and I was able to send and receive data packets.

**Comment by charlespax** [comment]
Got it. Closing issue.
